# Generated by Django 5.2.8 on 2025-11-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_score', models.IntegerField(default=0)),
                ('civic_score', models.IntegerField(default=0)),
                ('carbon_credits', models.FloatField(default=0)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('agent', 'Field Agent'), ('supervisor', 'Supervisor'), ('admin', 'Admin'), ('system', 'System / Bot')], default='citizen', max_length=20)),
                ('issues_reported', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('badge', models.CharField(default='Bronze', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
