# Generated by Django 5.2.8 on 2025-12-05 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_classification_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(choices=[('report_resolved_low', 'Report Resolved (Low Severity)'), ('report_resolved_medium', 'Report Resolved (Medium Severity)'), ('report_resolved_high', 'Report Resolved (High Severity)'), ('segregation_correct', 'Waste Segregation (Correct)'), ('false_report_penalty', 'False Report Penalty'), ('report_resolution_delay', 'Resolution Delay Penalty')], max_length=100, unique=True)),
                ('eco_points', models.IntegerField(default=0)),
                ('civic_points', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wastereport',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved'), ('invalid', 'Invalid/False Report')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('report_resolved', 'Report Resolved'), ('segregation_scan', 'Segregation Scan'), ('false_report', 'False Report Penalty'), ('service_redemption', 'Service Redemption'), ('admin_adjustment', 'Admin Adjustment')], max_length=50)),
                ('eco_points_change', models.IntegerField(default=0)),
                ('civic_points_change', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.wastereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
