# Generated by Django 5.2.8 on 2025-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pointrule_wastereport_points_awarded_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointRule',
        ),
        migrations.RemoveField(
            model_name='wastereport',
            name='points_awarded',
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='PointTransaction',
        ),
    ]
