# Generated by Django 5.2.8 on 2025-12-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0006_delete_pointrule_remove_wastereport_points_awarded_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in-progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("invalid", "Invalid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
