# Generated by Django 5.2.8 on 2025-12-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_wastereport_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CivicIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
