# Generated by Django 5.2.8 on 2025-12-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_appnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppNotification',
        ),
    ]
